### ISSUE TITLE
Found a broken recipe

### ISSUE THREAD

**Issue by ghost** [Brian-Wuest/MC-Repurpose#1]
If iI have installed your Mod the Framerate goes to allmost 0 when im joining my world. after deactivating the mod solves that behavior.
The Game does not crash just the FPS drops down to 0

Log: http://paste.ee/p/ubZFZ

**Comment by Brian-Wuest** [comment]
I do see the broken recipe error, however that seems to be for an item called "redbull_empty". I don't have an item called that in my mod. 

Also according to the log, the world save doesn't have my mod in it anymore (though it did before).

Was this the log from where the FPS was 0?

I tried to duplicate this issue by using the 1797 build of Forge for 1.9 and with 1.9.0.3 of the mod but was not able to duplicate the issue.

**Comment by Brian-Wuest** [comment]
Closing as there has been no response for additional information.
