### ISSUE TITLE
Channel name is too long, causes instant kick

### ISSUE THREAD

**Issue by maxhenkes** [Brian-Wuest/MC-Repurpose#10]
Forge 2094, test server, fresh map. Version 1.10.2.7
http://i.imgur.com/fbpDtMh.png
No issues

Updating to 1.10.2.8
http://i.imgur.com/ZARJkeK.png

https://github.com/Brian-Wuest/MC-WuestUtilities/blob/MC-1.10.2/src/main/java/com/wuest/utilities/Proxy/CommonProxy.java

WuestUtilities.network = NetworkRegistry.INSTANCE.newSimpleChannel("WuestUtilitiesChannel");

Your channel name is simply too long. A lot of things (like packets if I remember correctly) have this restriction. 

Also please please please stop archieving/deleting all your previous versions on curseforge. You now have a critical bug in your latest release and it's almost impossible to get a pack approved with the previous version included because I can't select it ..... At least leave the previous build alive until the next version, in case something like this happens.

**Comment by Brian-Wuest** [comment]
I am sorry that this happened. I can keep the previous version up longer.  What bugging me is that when I loaded up my world I didnt run into that error.

**Comment by Brian-Wuest** [comment]
I have restored 1.10.2.7 until this is fixed.

Going to kill 1.10.2.8 when this is fixed and release at 1.10.2.9. 1.10.2.7 will still be around.

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.10.2.9 which is now on curse forge. As suggested 1.10.2.7 will still be on the site and available.

**Comment by maxhenkes** [comment]
Thanks for the quick fix! :) Stuff happens. I also tested it on single player first and it worked, the server was what gave me issues. Also thanks for leaving the previous version alive, just a safety net in case something goes wrong! Thank you :)
