### ISSUE TITLE
The latest release is broken.

### ISSUE THREAD

**Issue by brisingraerowing** [Brian-Wuest/MC-Repurpose#11]
It contains TWO copies of the code.

How the ***\* did THAT happen?

**Comment by brisingraerowing** [comment]
Versions are 1.10.2.2 and 1.10.2.9

**Comment by Brian-Wuest** [comment]
Can you be more specific?

**Comment by Brian-Wuest** [comment]
Never-mind, I see it. No wonder my stuff has been broken like hell lately.

Fixing now.

**Comment by brisingraerowing** [comment]
Good!

Still, HOW does that happen?

**Comment by Brian-Wuest** [comment]
I have no freaking clue. I removed that release and I will be re-publishing. This has been an embarrassing past few days.....

**Comment by brisingraerowing** [comment]
My guess is a Gradle build caching derp.

**Comment by Brian-Wuest** [comment]
Yeah, that's what it looks like. I am just checking that everything works before I submit for a 3rd time.

That's what happens when I don't work on this thing for a month....

**Comment by brisingraerowing** [comment]
Having had virtually identical issues with many build systems across many languages, I think that caching old builds without causing issues is hard.

Oh, well. Thanks for fixing it so quickly!

**Comment by Brian-Wuest** [comment]
Alright.....this should now be fixed with the new 1.10.2.9. it is significantly smaller than the previous file and I made sure I can run it in normal Minecraft by itself.
