### ISSUE TITLE
Enable Step Assist

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Repurpose#12]
The current auto-jump implemented by Mojang get's players killed.

This enhancement is to allow the single player (or the server admin) to turn on step assist.

This option will not come into affect if the vanilla auto-jump is enabled.

The server configuration determines if this step assist will be applied to the player.

**Comment by brisingraerowing** [comment]
I turn the built in auto-jump off right away as it is horribly broken.

There is a mod that fixes it, but I could not get it to work. I should go back and see if it works now.

EDIT: [Here is the mod for reference](https://minecraft.curseforge.com/projects/stepupfixer?gameCategorySlug=mc-mods&projectID=248028)

**Comment by Brian-Wuest** [comment]
I can see if it works. If it does I will remove this enhancement.

**Comment by kaojinn** [comment]
A proposed change for this.  Default autojump is dangerous, a bit unpredictable, and can even prematurely waste your hunger bar.  However, the step-up ability that horses have is a powerful boon that, while not game breaking, should be earned through a little effort.

I propose creating it as an enchant that can be added to boots, that provides the step-up functionality.  This way if a player wants to get rid of it, they can always take the boots off, but it also makes the player deal with basic travel for a while before they can get the easy mode travel :)

Benefits of being an enchant:
Progress gated behind enchanting as a prerequisite.
Can work with any enchantable boots.
Mobs can spawn with it, giving zombies and skeletons a new level of hell to chase down players with!

Drawbacks of being an enchant:
Progress gated behind enchanting as a prerequisite.
Can work with any enchantable boots.
Mobs can spawn with it, giving zombies and skeletons a new level of hell to chase down players with!

**Comment by brisingraerowing** [comment]
@kaojinn Those are some good points. Were the benefits and drawbacks supposed to be the same, though?

**Comment by kaojinn** [comment]
Yes :)  My attempt at humor.  But in truth, as a matter of perspective, they can be viewed as both good and bad things, depending on the level of challenge the player prefers.  Personally, I like an absolutely punishing experience.  I feel all the more accomplished if I overcome it :)

**Comment by brisingraerowing** [comment]
Heh. I have no combat skills whatsoever, so I usually play in creative (and I still fail at killing mobs. I usually end up falling off a cliff/down a hole). I switch to survival/peaceful to mine sometimes, but that's about it.

**Comment by Brian-Wuest** [comment]
So what I have so far.

An enchantment called "Step Assist". It will have up to 3 levels and is a common enchantment.
1st level gives the player 1 block step assist. This way they can go up 1 block inclines.
2nd level gives the player 1.5 block step assist. This way they can go up fences/walls.
3rd level gives the player 2 block step assist. This makes it much easier to go up/around mountains.

Because there is no armor equip/unequip event I have to check on each player tick if they have boots with this enchantment and adjust their StepHeight property based on the level. 

I will keep track of what their original step height was and what I changed it too. This way when they un-equip the boots I can reset the player's step height to what my mod knows it is supposed to be. This can be a bit tricky with other mods doing step assist things (like botania's baubles). But since this happens on every tick it should be fine.

**Comment by Brian-Wuest** [comment]
Oh I am also going to make sure that if the player has step assist form another mod that the enchantment level represents the maximum allowed step height.

So of they already have a step height of 1 from the botania bauble and enchant some boots with step assist 1, their step height would stay at 1.

**Comment by Brian-Wuest** [comment]
This feature has been implemented in 1.10.2.10 and is now available on curseforge. Have fun!
