### ISSUE TITLE
Query:  1.11.2?

### ISSUE THREAD

**Issue by IamAlathe** [Brian-Wuest/MC-Repurpose#14]
I think I'm addicted to your mods. 😉 I know you got prefab to 1.11.2, and I see you got this one to 1.11, so I was just wondering if I'll be able to use your utilities in 1.11.2 sometime in the near(ish) future.  Thanks for some great mods. 😃

**Comment by Brian-Wuest** [comment]
The existing file ahould already work for 1.11.2. I can check later today.

**Comment by Brian-Wuest** [comment]
A 1.11.2 version of this mod has been made available on CurseForge. Link here: https://minecraft.curseforge.com/projects/wuestutilities/files/2378268

Thanks for bringing this up! I had to do a fair amount of changes.
