### ISSUE TITLE
[feature request] add brief descriptions of items

### ISSUE THREAD

**Issue by Zygus42** [Brian-Wuest/MC-Repurpose#19]
Could you please add brief descriptions of the items and blocks, either as tooltips or info tabs in JEI.  

Would be nice if people on my server saw an item called "Redstone Scanner" and could tell that it "Can scan in a radius around it to detect entities and generates a redstone signal if it finds one."

**Comment by Brian-Wuest** [comment]
I sure can add that!

Thank you for the suggestion!

**Comment by Brian-Wuest** [comment]
This has been added with version 1.0.0.1 which has been released on curseforge.

Thank you!
