### ISSUE TITLE
[1.9.4] WuestUtilities breaks EnderIO Powered Spawner Anvil Recipe

### ISSUE THREAD

**Issue by Melakion** [Brian-Wuest/MC-Repurpose#2]
Forge 1962
wuestUtilities-1.9.4.6
EnderCore-1.9.4-0.4.0.24-alpha
EnderIO-1.9.4-3.0.0.40_alpha

EnderIO Powered Spawner anvil combine with Broken Spawner doesn't work with wuestUtilities installed.
https://github.com/SleepyTrousers/EnderIO/issues/3398

**Comment by Melakion** [comment]
I'm told https://github.com/Brian-Wuest/MC-WuestUtilities/blob/MC-1.9.4/src/main/java/wuest/utilities/Events/WuestEventHandler.java#L230 will break other anvil recipes.

**Comment by Brian-Wuest** [comment]
Thank you, I saw the thread and addressed with version 1.9.4.7.

This was just uploaded to curse forge.

Closing issue.
