### ISSUE TITLE
Additional feature request for Redstone Clock

### ISSUE THREAD

**Issue by brisingraerowing** [Brian-Wuest/MC-Repurpose#24]
It would be nice to be able to disable the redstone clock by giving it a signal, like the one from Cyclic. I use a clock to cast molten metal from a smeltery, and I don't want that running all the time. I currently have a workaround by sending the clock signal into a repeater, into a block on a sticky piston that acts as a switch.

**Comment by Brian-Wuest** [comment]
Makes sense, I can get that done 😄 .

**Comment by Brian-Wuest** [comment]
Updated with 1.0.0.10 just uploaded to curse forge.
