### ISSUE TITLE
Bag of Holding

### ISSUE THREAD

**Issue by kaojinn** [Brian-Wuest/MC-Repurpose#26]
Just kickin around an idea for terraforming tools.  There's plenty that lets you pick it up or clear away quickly, but not much that lets you place it back down quickly.  The idea is a sack that will automatically grab plant matter, and ground blocks that arent stone, and let you quickly select them from the bag, and place them down with a simple right click.

First off, the bag would be an item that would go in your offhand, akin to a shield.  Right clicking with it equipped would allow you to place whatever block is currently selected.  The bag will have 64 inventory slots for storage, and 1 that holds the stack of whatever is selected to be placed.  

Right click while targeting nothing: Open bag inventory
Right click while targeting a block face: place block/item from slot 0 of the bag's inventory
Right click with item in hand that either has a right click function, or can be placed in the world: bag is ignored, existing item/tool should maintain normal functionality.

Bag should also have a hotkey, and a list of contents that can be easily selected on the fly.

Items picked up should go to the equipped bag's inventory first, provided they are on the bag's filter of items to collect.  Initially thinking stuff like Seeds, Saplings, Dirt, Grass, Leaves, Wood, Vines, Flowers, Sand, Gravel, Clay Blocks, that kinda stuff.

**Comment by Brian-Wuest** [comment]
Released with 1.0.0.11 on curse forge.
