### ISSUE TITLE
Really bizarre bug

### ISSUE THREAD

**Issue by brisingraerowing** [Brian-Wuest/MC-Repurpose#28]
With 1.0.0.13, I am getting Forestry taking over your items (e.g. the redstone clock). This does not happen with 1.0.0.12, so I would assume it's on your end. It still boggles the mind that something like this could happen, though.

I'll get a screenshot if requested.

Forge: 2654
MC: 1.12.2

**Comment by Brian-Wuest** [comment]
Yes, a screenshot would be appreciated. Not sure how Forestry would be taking over my blocks/items. Especially the Redstone Clock. I haven't changed that in ages!

Also; how did you narrow it down to Forestry?!

**Comment by Brian-Wuest** [comment]
Also, what version of Forestry are you running? It looks like they updated a couple of times today.

**Comment by brisingraerowing** [comment]
Currently the latest as of this post. On mobile RN so CBA to get the actual version from CF. Same issue with the two previous versions as well.

**Comment by Brian-Wuest** [comment]
k, I understood RN and CF, what's CBA?

After work I will pull forestry and see what happened.

**Comment by brisingraerowing** [comment]
Can't be arsed.

**Comment by Brian-Wuest** [comment]
ha! nice!

**Comment by Brian-Wuest** [comment]
I just tried this in my development environment which has the same code as which was uploaded in the last release and it appears to be working fine.

I just have Forestry, JEI and Repurpose running. 

Was this on a dedicated server setup or were there other mods involved in your setup?

I also set it up and it works fine with a triggering redstone and opening a door.

![2018-04-20_16 48 26](https://user-images.githubusercontent.com/13502068/39075375-efa01184-44ba-11e8-9442-b4b7cbc282aa.png)

![2018-04-20_16 52 50](https://user-images.githubusercontent.com/13502068/39075469-55997f7a-44bb-11e8-8e22-af47115ef8dd.png)

**Comment by brisingraerowing** [comment]
I'll have to run a check with my other mods and see what's going on.
EDIT: It might be a bit, I'm currently trying to figure out what is causing worldgen lag when there is a desert in the loading chunks. It's only desert that lags, all other biomes are perfectly fine.
EDIT2: I'm going to try updating Forge and see it that helps, then I'll try a process of elimination to find the incompatibility. That shouldn't take too  long, as my minimal IE-centric pack displays the issue, so it is a common mod between my two main packs.

**Comment by brisingraerowing** [comment]
I think my IE instance may have some data corruption, as my main pack does not display the issue with the same mod versions.

**Comment by brisingraerowing** [comment]
I recreated the instance and the issue went away. I'm still curious as to what kind of data corruption could have caused this, though. It's definitely a weird one.

**Comment by Brian-Wuest** [comment]
I am glad that it got striaghtened out. Though it is the weirdest issue I have seen!
