### ISSUE TITLE
Don't pass TileData to writeToNBT

### ISSUE THREAD

**Issue by LXGaming** [Brian-Wuest/MC-Repurpose#30]
This issue was found while debugging why our Engineers Life server was randomly freezing.

Related issue: https://www.curseforge.com/minecraft/mc-mods/repurpose/issues/6

https://github.com/Brian-Wuest/MC-Repurpose/blob/691cfeb37876f8f63b38c022dd9e761ce3e53034/src/main/java/com/wuest/repurpose/Base/TileEntityBase.java#L131-L136

In the `TileEntityBase::onChunkUnload` method you're passing the TileData to `writeToNBT`, This is a huge issue as Forge writes the TileData in `TileEntity::writeToNBT` under a `ForgeData` key, This is later causing Infinite loops / StackOverflow errors to occur due to the TileData containing itself.

Also note that this problematic code seems to exist in multiple versions (Minecraft versions) of this mod and [FromTheDepths](https://github.com/Brian-Wuest/MC-FromTheDepths/blob/d854ba0d5de5fd597d08cf13beba7497d854fe29/src/main/java/com/wuest/from_the_depths/Base/TileEntityBase.java#L143-L151)

**Comment by Brian-Wuest** [comment]
Wow, that's a pretty nasty bug. Very sorry about that.

From analysis it seems that the method isn't necessary at all.

I will remove it and test out my tile entities before pushing my first release in like 2 years!

**Comment by Brian-Wuest** [comment]
This has been fixed and released with version 1.0.0.20 on curseforge.

Thank you!

Closing Issue
