### ISSUE TITLE
Stone shears don't work on pumpkins (1.15.2)

### ISSUE THREAD

**Issue by SwanX1** [Brian-Wuest/MC-Repurpose#33]
All the information I have is in the title.

**Comment by Brian-Wuest** [comment]
More description of what exactly is the problem would be appreciated. Eventually I figured out that you meant that you can't right-click on a pumpkin to turn it into a pumpkin with a face (Jack-o'-lantern).

Unfortunately; custom shears cannot do this.

In the below screen shot I show that the Pumpkin block is specifically looking for the vanilla shears.
Forge would need to put in a patch to fix this.

![image](https://user-images.githubusercontent.com/13502068/87235780-5d445180-c3a5-11ea-9a48-7fa5244c380c.png)
