### ISSUE TITLE
Unnamed LootPool strikes back

### ISSUE THREAD

**Issue by Aizistral** [Brian-Wuest/MC-Repurpose#34]
Basically, this line of code:

https://github.com/Brian-Wuest/MC-Repurpose/blob/ff3a994089e13764205b46bf73112b82c9ab26b4/src/main/java/com/wuest/repurpose/Events/WuestEventHandler.java#L465

You should always name `LootPool`s you inject by calling `LootPool.Builder#name(String)`. Set it to whatever, just make sure that whatever is not `null`. Otherwise you will cause an error state if any other mod attempts to inject to the same table, which in turn leads to no loot being generated from affected loot table.

**Comment by Brian-Wuest** [comment]
This was fixed in 1.4.0.1
