### ISSUE TITLE
Issue on server running

### ISSUE THREAD

**Issue by Chrisjohnson57387** [Brian-Wuest/MC-Repurpose#35]
Howdy, I'm getting this issue when running this on a server, but not in my client. LMK if you need any more info.

?7java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.wuest.repurpose.Items.ItemBagOfHolding.<init>()void/newInvokeSpecial

**Comment by Brian-Wuest** [comment]
Interesting; thought I tested this on dedicated servers when I first released it.

Something must have broken it; will get it tested out again and push out an update.

Thank you for finding this!

**Comment by Brian-Wuest** [comment]
This has been fixed 1.4.0.2 and is now available on curse forge.

Thank you!

**Comment by Chrisjohnson57387** [comment]
Thank you!
