### ISSUE TITLE
JSON crash report

### ISSUE THREAD

**Issue by Denubis** [Brian-Wuest/MC-Repurpose#4]
https://gist.github.com/Denubis/d329b62bbb5c53293ef91e74f0720620

Was running on prior version. Seems to be trying to parse JSON. Updated to .4, failed. removed config file, failed.

**Comment by brisingraerowing** [comment]
This is a duplicate of #3

**Comment by Brian-Wuest** [comment]
Closing, this issue will be tracked with #3.
