### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by ghost** [Brian-Wuest/MC-Repurpose#6]
Server still won't start with the updated version. Client seems to be working fine.

http://pastebin.com/ZZEH5mJK

Forge 2070
Wuest 1.10.2.5

**Comment by Brian-Wuest** [comment]
I noticed that this morning as well while working on the update checker configuration option.

This will be fixed later today.

**Comment by Brian-Wuest** [comment]
1.10.2.6 has been released which addresses this issue.

Closing.
